# Generated by Django 4.2.8 on 2023-12-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.base')),
                ('tag', models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket')),
                ('name', models.CharField(max_length=500, verbose_name='Adı')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Konum')),
                ('manufacturer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Üretici')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=500, null=True, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Seri Numarası')),
                ('product_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ürün Numarası')),
                ('inventory_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Stok Numarası')),
                ('used_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kullanan Birim / Kullanıcı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
            ],
            bases=('entity.base',),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Durum Adı')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Durum',
                'verbose_name_plural': 'Durumlar',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Port Adı')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Portlar',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
            ],
            options={
                'verbose_name': 'Bilgisayar',
                'verbose_name_plural': 'Bilgisayarlar',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
            ],
            options={
                'verbose_name': 'Aygıt',
                'verbose_name_plural': 'Aygıtlar',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('ip_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='IP Adresi')),
            ],
            options={
                'verbose_name': 'Ağ Cihazı',
                'verbose_name_plural': 'Ağ Cihazları',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('license_key', models.TextField(blank=True, null=True, verbose_name='Lisans Anahtarı')),
                ('license_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Lisans Başlangıç Tarih / Saat')),
                ('license_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Lisans Bitiş Tarih / Saat')),
            ],
            options={
                'verbose_name': 'Yazılım',
                'verbose_name_plural': 'Yazılımlar',
            },
            bases=('entity.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.status', verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('ports', models.ManyToManyField(to='entity.port', verbose_name='Portlar')),
            ],
            options={
                'verbose_name': 'Yazıcı',
                'verbose_name_plural': 'Yazıcılar',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Boyut')),
                ('ports', models.ManyToManyField(to='entity.port', verbose_name='Portlar')),
            ],
            options={
                'verbose_name': 'Monitör',
                'verbose_name_plural': 'Monitörler',
            },
            bases=('entity.entity',),
        ),
    ]
