# Generated by Django 5.1.3 on 2024-12-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('license_key', models.TextField(blank=True, null=True, verbose_name='Lisans Anahtarı')),
                ('license_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Lisans Başlangıç Tarih / Saat')),
                ('license_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Lisans Bitiş Tarih / Saat')),
            ],
            options={
                'verbose_name': 'Lisans',
                'verbose_name_plural': 'Lisanslar',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='LicenseSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.session')),
                ('license_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.license', verbose_name='Lisans')),
            ],
            options={
                'verbose_name': 'Lisans Oturum/Giriş Bilgisi',
                'verbose_name_plural': 'Lisans Oturum/Giriş Bilgileri',
            },
            bases=('entity.session',),
        ),
    ]
